config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :hearts, only: :create
  resources :authors
  resources :author_sessions, only: [ :new, :create, :destroy ]

  get 'login'  => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
  get 'blog' => 'pages#blog'

  root 'pages#welcome'

end

app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!

  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/heart.rb
class Heart < ActiveRecord::Base
	belongs_to :post
	validates :post_id, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :hearts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
  def new
  end

  def create
    if login(params[:email], params[:password])
      redirect_back_or_to(posts_path, notice: 'Logged in successfully')
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(root_url, notice: 'Logged out!')
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_filter :require_login, except: [:new, :create]
  before_filter :zero_authors_or_authenticated, only: [:new, :create]
  # GET /authors
  # GET /authors.json


  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end

  def zero_authors_or_authenticated
    unless Author.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end
end

app/controllers/hearts_controller.rb
class HeartsController < ApplicationController
  before_filter :require_login, only: [:destroy]
  
  def create
    @heart = Heart.new(heart_params)
  
    if @heart.save
      redirect_to @heart.post, notice: 'Hearted that post!'
    else
      redirect_to root_url, notice: "Had an issue creating that heart."
    end
  end




  private
  def heart_params
    params.require(:heart).permit(:post_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def blog
  	@posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :require_login, only: [:new, :create, :update, :destroy]
  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

      if @post.save
        redirect_to @post, notice: 'Post was successfully created.'
      else
        render :new
      end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :kind, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/author_sessions/new.html.erb
<% content_for :banner do %>
      style="background-image: url('../assets/home-bg.jpg')"
    <% end %>

<% content_for :header do %>
  <h1>The Best Website Ever</h1>
  <hr class="small">
  <span class="subheading">Only I can log in. I hope.</span>
<% end %>



<% content_for :body do %>
<h1>Login</h1>

<%= form_tag author_sessions_path, method: :post do %>
  <div class="form-group">
    <%= label_tag :email %><br/>
    <%= text_field_tag :email,"",class: 'form-control' %>
    <br/>
  </div>
  <div class="form-group">
    <%= label_tag :password %><br/>
    <%= password_field_tag :password,"",class: 'form-control' %>
    <br/>
  </div>
  <div class="actions">
    <%= submit_tag "Login",class: 'btn btn-primary' %>
  </div>
<% end %>

<% end %>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Authors</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.username %></td>
        <td><%= author.email %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <link rel='shortcut icon' href='assets/favicon.ico' type='image/x-icon'/ >

  <title>Nathan Louie</title>

  <!-- Bootstrap Core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


  <!-- application.css file -->
  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- fonts awesome -->
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">


  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>
  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header page-scroll">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              Menu <i class="fa fa-bars"></i>
          </button>
          <a class="navbar-brand" href=<%= root_url %>>NL</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_url %></li>
          <li><%= link_to "Blog", blog_url %></li>
          <% if logged_in? %>
            <li><%= link_to "Manage Posts", posts_url %></li>
            <li><%= link_to "Log Out", logout_path %></li>
          <%else%>
            <li><%= link_to "Log In", login_path %></li>
          <% end %>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
  <!-- /.container -->
  </nav>


  <!-- Yield Banner -->
  <header class="intro-header" <%= yield :banner %>>
      <div class="container">
          <div class="row">
              <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                  <div class="site-heading">
                      <%= yield :header %>
                  </div>
              </div>
          </div>
      </div>
  </header>


  <!-- Yield Body -->
  <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= yield :body %>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
      <div class="container">
          <div class="row">
              <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                  <ul class="list-inline text-center">
                      <li>
                          <a href="https://www.linkedin.com/in/nxlouie" target="_blank">
                              <span class="fa-stack fa-lg">
                                  <i class="fa fa-circle fa-stack-2x"></i>
                                  <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                              </span>
                          </a>
                      </li>
                      <li>
                          <a href="https://www.facebook.com/nxlouie" target="_blank">
                              <span class="fa-stack fa-lg">
                                  <i class="fa fa-circle fa-stack-2x"></i>
                                  <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                              </span>
                          </a>
                      </li>
                      <li>
                          <a href="https://www.github.com/nxlouie" target="_blank">
                              <span class="fa-stack fa-lg">
                                  <i class="fa fa-circle fa-stack-2x"></i>
                                  <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                              </span>
                          </a>
                      </li>
                  </ul>
                  <p class="copyright text-muted">Copyright &copy; Nathan Louie 2016</p>
              </div>
          </div>
      </div>
  </footer>

  <!-- jQuery -->
  <script src="assets/jquery.min.js"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="assets/bootstrap.min.js"></script>

  <!-- Contact Form JavaScript -->
  <script src="assets/jqBootstrapValidation.js"></script>
  <script src="assets/contact_me.js"></script>

  <!-- Theme JavaScript -->
  <script src="assets/clean-blog.min.js"></script>

</body>

</html>

app/views/pages/blog.html.erb
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <% content_for :banner do %>
        style="background-image: url('assets/contact-bg.jpg')"
    <% end %>

    <% content_for :header do %>
        <h1>Blog</h1>
            <hr class="small">
            <span class="subheading">Tech Life and Stuff</span>
    <% end %>

    <!-- Main Content -->
    <% content_for :body do %>
    <% @posts.each do |post| %>

      <%= render 'posts/post', post: post %>
      <br><br><br><br>
    <% end %>
    <% end %>
  <hr>

app/views/pages/welcome.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->

<% content_for :banner do %>
    style="background-image: url('assets/coffee.jpg')"
<% end %>

<% content_for :header do %>
  <img src="assets/me.jpg" class="img-circle" alt="This is me" width="175" height="175">
  <h1>Nathan Louie</h1>
  <hr class="small">
  <span class="subheading">Software Developer</span>
<% end %>


<!-- Main Content -->
<% content_for :body do %>
<div>
    <div>
      <h2>About Me</h2>
      <p>Junior, Pursuing a Bachelor's Degree in Computer Science at the <a href="http://umich.edu/" target="_blank">University of Michigan</a>. Seeking a high impact internship for Summer 2017.</p>

      <p>Here is my <a href="assets/Louie_Nathan_Resume.pdf" target="_blank">Resume</a>!</p>

      <p>I am passionate about Computer Science because of the innate amount of collaboration involved in the discipline. I appreciate the idea that writing good, reusable code involves both in-depth technical knowledge, and teamwork skills in order to work effectively.</p>

      <br>

      <h2>Languages and Frameworks</h2>
      <li>Curriculum: C++, C, Python, SQL</li>
      <li>Work Experience: C#, VBA, VB.NET</li>
      <li>Hobby: JavaScript, Ruby on Rails</li>

      <br><br>

      <h2>Activities & Involvement</h2>
      <li><a href="http://www.theodinproject.com/" target="_blank">Learning Web Development</a> in my free time</li>
      <li>Vice President of Theta Tau, Professional Engineering Fraternity</li>
      <li>Member of Club Swimming at the University of Michigan</li>
      <li>History buff & avid reader</li>
    </div>
</div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :kind %><br>
    <%= f.select :kind, ["text", "image"],{},class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<p>
 	<h2>
 	<div class="pull-right">
 		<%= form_for(Heart.new) do |f| %>
 			<%= f.hidden_field :post_id, value: post.id %>
 			<%= f.submit "♥", class: 'btn btn-danger' %>
 		<% end %>
 	</div>
 	<%= link_to post.title, post %>
 	</h2>
</p>

<p>
	<% if post.kind == 'image' %>
		<%= image_tag post.content, style: "width: 100%" %>
	<% else %>
  		<%= simple_format(post.content) %>
  	<% end %>
</p>

<p class="text-muted">
<small>
<%= post.created_at.to_formatted_s(:long) %>
</small>

<small class="pull-right">
<%= post.hearts.count %> hearts
</small>
</p>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<% content_for :body do %>
<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
<% end %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

    <% content_for :banner do %>
        style="background-image: url('assets/home-bg.jpg')"
    <% end %>

    <% content_for :header do %>
        <h1>Manage Posts</h1>
        <hr class="small">
        <span class="subheading">No one should see this but me......</span>
    <% end %>


<% content_for :body do %>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= truncate(post.content, length: 100) %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>
<% end %>

app/views/posts/new.html.erb
<% content_for :body do %>
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>
<% end %>

app/views/posts/show.html.erb
<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>

<% content_for :banner do %>
      style="background-image: url('../assets/post-bg.jpg')"
    <% end %>

<% content_for :header do %>
  <h1>Post Title</h1>
  <hr class="small">
  <span class="subheading">Post View zzzzzz</span>
<% end %>

<% content_for :body do%>
  <%= render 'post', post: @post %>
<% end %>